# Generated by Django 5.2.3 on 2025-06-24 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Banking', '0003_alter_user_cellulare'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('importo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descrizione', models.CharField(max_length=255)),
                ('conto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transazioni', to='Banking.contocorrente')),
            ],
        ),
    ]
