# Generated by Django 5.2.3 on 2025-07-06 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Banking', '0004_transazione'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transazione',
            name='conto',
        ),
        migrations.AddField(
            model_name='transazione',
            name='causale',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transazione',
            name='conto_destinazione',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transazioni_entrata', to='Banking.contocorrente'),
        ),
        migrations.AddField(
            model_name='transazione',
            name='conto_sorgente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transazioni_uscita', to='Banking.contocorrente'),
        ),
        migrations.AddField(
            model_name='transazione',
            name='tipo',
            field=models.CharField(choices=[('bonifico', 'Bonifico'), ('invio_soldi_amico', 'Invio soldi ad amico')], default='bonifico', max_length=30),
        ),
    ]
