# Generated by Django 5.2.3 on 2025-07-06 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Banking', '0005_remove_transazione_conto_transazione_causale_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transazione',
            name='descrizione',
        ),
    ]
