# Generated by Django 5.2.3 on 2025-07-11 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Banking', '0006_remove_transazione_descrizione'),
    ]

    operations = [
        migrations.AddField(
            model_name='contocorrente',
            name='consulente',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'consulenti'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clienti_associati', to=settings.AUTH_USER_MODEL),
        ),
    ]
